import { StyleSheet } from "react-native";

export const theme = {
  bg: "#F2FAF8",
  surface: "#FFFFFF",
  surfaceAlt: "#E2F4F0",
  text: "#04323A",
  textMuted: "#315B60",
  accent: "#0F766E",
  danger: "#A12622",
  ok: "#166534",
  border: "#B8D8D2",
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.bg, padding: 24 },
  scrollScreen: { flex: 1, backgroundColor: theme.bg },
  scrollContent: { padding: 24, paddingBottom: 40, flexGrow: 1 },
  title: { color: theme.text, fontSize: 32, lineHeight: 40, fontWeight: "700", marginBottom: 8 },
  subtitle: { color: theme.textMuted, fontSize: 18, lineHeight: 26, marginBottom: 24 },
  card: {
    backgroundColor: theme.surface,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: theme.border,
  },
  cardTitle: { color: theme.text, fontSize: 21, lineHeight: 28, fontWeight: "700" },
  cardMeta: { color: theme.textMuted, fontSize: 16, lineHeight: 24, marginTop: 6 },
  button: {
    backgroundColor: theme.accent,
    borderRadius: 14,
    minHeight: 60,
    paddingVertical: 16,
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  buttonText: { color: "#FFFFFF", fontSize: 19, lineHeight: 26, textAlign: "center", fontWeight: "700" },
  buttonAlt: {
    backgroundColor: theme.surface,
    borderWidth: 2,
    borderColor: theme.accent,
    borderRadius: 14,
    minHeight: 60,
    paddingVertical: 16,
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  buttonAltText: { color: theme.accent, fontSize: 19, lineHeight: 26, textAlign: "center", fontWeight: "700" },
  input: {
    backgroundColor: theme.surface,
    color: theme.text,
    borderColor: "#648C85",
    borderWidth: 2,
    borderRadius: 12,
    minHeight: 60,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 19,
    marginBottom: 16,
  },
  label: { color: theme.text, fontSize: 18, lineHeight: 25, fontWeight: "700", marginBottom: 8 },
  choice: { backgroundColor: theme.surface, borderColor: "#648C85", borderWidth: 2, borderRadius: 12, minHeight: 56, justifyContent: "center", paddingHorizontal: 16, paddingVertical: 12, marginBottom: 8 },
  choiceSelected: { backgroundColor: theme.surfaceAlt, borderColor: theme.accent, borderWidth: 3 },
  choiceText: { color: theme.text, fontSize: 18, lineHeight: 24, fontWeight: "600" },
  choiceSelectedText: { color: theme.accent, fontSize: 18, lineHeight: 24, fontWeight: "700" },
  error: { color: theme.danger, fontSize: 17, lineHeight: 24, fontWeight: "600", marginBottom: 8 },
  ok: { color: theme.ok, fontSize: 18, lineHeight: 26, fontWeight: "700" },
});
